### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by emily-brooklinen** [jirikuchta/garmin-ical-export#2]
Hi!
I'm so glad you took the time to write this.  I know it's been a year, but I'm looking to export all my activities and I'm getting the following error "ZeroDivisionError: float division by zero". 

I'm unfamiliar with python so I can't figure out a solve. 

I know it's been awhile, but if you're still maintaining this I thought I would ask :). 

Cheers!

`emilymccormick garmin-ical$ garmin-ical-export \<email\> \<password\> --activity_type all --target_file ~/garmin_activities.ics

Traceback (most recent call last):
  File "/Users/emilymccormick/Library/Python/3.9/bin/garmin-ical-export", line 8, in <module>
    sys.exit(main())
  File "/Users/emilymccormick/Library/Python/3.9/lib/python/site-packages/garminicalexport/cmd.py", line 52, in main
    ical = to_ical(login_data, args.limit,
  File "/Users/emilymccormick/Library/Python/3.9/lib/python/site-packages/garminicalexport/__init__.py", line 22, in to_ical
    event.add("summary").value = activity.ical_summary
  File "/Users/emilymccormick/Library/Python/3.9/lib/python/site-packages/garminicalexport/activities.py", line 106, in ical_summary
    return f"{self.name} ({self.distance}, {self.average_speed})"
  File "/Users/emilymccormick/Library/Python/3.9/lib/python/site-packages/garminicalexport/activities.py", line 100, in average_speed
    return format_utils.speed_minutes_per_kilometer(speed)
  File "/Users/emilymccormick/Library/Python/3.9/lib/python/site-packages/garminicalexport/format_utils.py", line 33, in speed_minutes_per_kilometer
    minutes, seconds = divmod(1000 / meters_per_second, 60)
ZeroDivisionError: float division by zero`

**Comment by jirikuchta** [comment]
Hi Emily, thanks for the bugreport.

Seems like one or more of your activities have zero speed which leads to the error during string formatting.

The issue should be solved in version 1.0.5. Please reinstall the package and try once more.

**Comment by filipsPL** [comment]
Unfortunately this issue is still there in 1.0.5:

```
$ pip freeze | grep garmin
garmin-ical-export==1.0.5
```

```
Traceback (most recent call last):
  File "/home/username/.local/bin/garmin-ical-export", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.9/site-packages/garminicalexport/cmd.py", line 52, in main
    ical = to_ical(login_data, args.limit,
  File "/home/username/.local/lib/python3.9/site-packages/garminicalexport/__init__.py", line 22, in to_ical
    event.add("summary").value = activity.ical_summary
  File "/home/username/.local/lib/python3.9/site-packages/garminicalexport/activities.py", line 134, in ical_summary
    return f"{self.name} ({self.distance}, {self.average_speed})"
  File "/home/username/.local/lib/python3.9/site-packages/garminicalexport/activities.py", line 130, in average_speed
    return format_utils.speed_minutes_per_100_metres(speed)
  File "/home/username/.local/lib/python3.9/site-packages/garminicalexport/format_utils.py", line 28, in speed_minutes_per_100_metres
    minutes, seconds = divmod(100 / meters_per_second, 60)
ZeroDivisionError: float division by zero
```

I guess simple `try` would solve this problem...

**Comment by jirikuchta** [comment]
The `try` statement is already [there](https://github.com/jirikuchta/garmin-ical-export/blob/master/garminicalexport/format_utils.py#L28). 

What does the `/home/username/.local/lib/python3.9/site-packages/garminicalexport/format_utils.py` file looks like? Do you see the `try` on line 28? Chances are you still have older version installed.

**Comment by filipsPL** [comment]
Thanks for your prompt reply, @jirikuchta. Indeed, the problem was due to double-python-environment I have in the system. While conda env generated some other issues (see #1 ) I had to install it locally. But when upgraded with pip, it was upgrading the version in the conda env.

For the future reference: if conda env is activated, deactivate it and then install/upgrade the package.
